# Generated by Django 5.2 on 2026-02-07 20:07

import django.db.models.deletion
import django_multitenant.mixins
import django_multitenant.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ejemplo: Administrador, Vendedor, Editor', max_length=100, verbose_name='Nombre del Rol')),
                ('description', models.TextField(blank=True, help_text='Breve descripción de las responsabilidades de este rol.', verbose_name='Descripción')),
                ('is_protected', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='sandbox.organization')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Selecciona los permisos específicos que tendrá este rol dentro del tenant.', to='auth.permission', verbose_name='Permisos')),
            ],
            options={
                'verbose_name': 'Rol de Negocio',
                'verbose_name_plural': 'Roles de Negocio',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('organization', 'name')},
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_protected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(help_text='El usuario que pertenece a este espacio de trabajo.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='sandbox.organization')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='sandbox.role')),
            ],
            options={
                'unique_together': {('organization', 'user')},
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
    ]
